services:
  db:
    build:
      context: ./docker/db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  pgadmin:
    build:
      context: ./docker/pgadmin
    restart: always
    ports:
      - "5000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - "db"
volumes:
  pg-data:
  pgadmin-data:

